name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
      - "buildx"

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
