name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11"]
        toxenv: [py]
        include:
          - python: "3.10"
            toxenv: flake8
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install wireguard-tools
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: python -m pip install --upgrade tox poetry
      - run: tox -e ${{ matrix.toxenv }}
  all-tests-succeeded:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - name: All tests succeeded
        run: echo "🎉"
