name: Release

on:
  push:
    branches:
      - "buildx"
  release:
    types: [published]


jobs:
  pypi:
    env:
      # POETRY_HOME: ${{ runner.temp }}/.poetry
      POETRY_VERSION: "1.3.2"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      # - run: echo "${POETRY_HOME}/bin" >> ${GITHUB_PATH}
      # - name: Install Poetry
      #   run: |
      #     python -m venv "${POETRY_HOME}" \
      #     && "${POETRY_HOME}/bin/pip" install -U pip==22.2.2 wheel==0.37.1 setuptools==65.3.0 \
      #     && "${POETRY_HOME}/bin/pip" install "poetry==${POETRY_VERSION}"
      - run: poetry --version
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/wg-wizard:latest
